### ISSUE TITLE
Make the root URL redirect to /current

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-documentation-ui#24]
Currently, if you access the root of the jakarta-tutorial path, you get an error. We'd like it to forward you to `/current/index.html`.

To be more precise: 

Currently:

* https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/9.1/ displays Jakarta EE 9.1 tutorial
* https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/ displays Jakarta EE 10 turorial
* https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/ yields a 404, but we want it to redirect to https://jakartaee.github.io/jakartaee-documentation/jakartaee-tutorial/current/

**Comment by kito99** [comment]
@jhammen :-)

**Comment by jhammen** [comment]
should  be good, see new PR above
