### ISSUE TITLE
Clicking on the Jakarta EE logo on the type left redirects to the wrong URL.

### ISSUE THREAD

**Issue by kito99** [jakartaee/jakartaee-documentation-ui#38]
When you click on the Jakarta EE logo, it should go to https://jakarta.ee/learn/docs/jakartaee-tutorial/current/, but instead it goes to https://jakarta.ee/learn/jakartaee-tutorial/current/index.html. 

![2024-09-06_12-45-14](https://github.com/user-attachments/assets/c37b413a-53a4-4b0c-b442-93107e425ecd)

**Comment by MangosPage** [comment]
Hey, I'm willing to participate .

**Comment by kito99** [comment]
Thanks, @MangosPage! Looks like @Ndacyayisenga-droid addressed this in https://github.com/jakartaee/jakartaee-documentation/pull/26.
